import{BarChart3,Pause,Play,RotateCcw}from'lucide-react';
import{useState}from'react';
import{useTranslation}from'../i18n';
import{useFocusTimer}from'./FocusTimerContext';

function format(seconds:number){return`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}

type Props={mode:'foreground'|'wallpaper';onOpenStatistics:()=>void};

export function FocusTimerWidget({mode,onOpenStatistics}:Props){
 const{t}=useTranslation();const timer=useFocusTimer();const[minutes,setMinutes]=useState(timer.state.plannedSeconds/60);const[customOpen,setCustomOpen]=useState(false);const[custom,setCustom]=useState('');const customValue=Number(custom);const customValid=Number.isInteger(customValue)&&customValue>=1&&customValue<=720;const running=timer.state.status==='running';const paused=timer.state.status==='paused';
 if(mode==='wallpaper')return <div className="widget-content focus-timer focus-timer--wallpaper"><div className="panel-body focus-timer__body"><p className="focus-timer__display" role="timer">{format(timer.remainingSeconds)}</p><p className="focus-timer__hint">{t('focusTimer.wallpaperHint')}</p></div></div>;
 return <div className="widget-content focus-timer"><div className="card-header focus-timer__header"><button className="btn btn-icon" aria-label={t('focusTimer.statistics')} onClick={onOpenStatistics}><BarChart3 aria-hidden="true"/></button></div><div className="panel-body focus-timer__body"><p className="focus-timer__display" role="timer">{format(timer.remainingSeconds)}</p><p className="focus-timer__hint">{running?t('focusTimer.runningHint'):paused?t('focusTimer.pausedHint'):t('focusTimer.idleHint')}</p><div className="focus-timer__presets">{[25,15,5].map(value=><button key={value} className={`btn focus-timer__preset${minutes===value?' is-active':''}`} aria-label={`${value} ${t('focusTimer.preset25').replace('25 ','')}`} onClick={()=>setMinutes(value)}>{value} {t('focusTimer.preset25').replace('25 ','')}</button>)}<button className="btn focus-timer__preset" onClick={()=>setCustomOpen(value=>!value)}>{t('focusTimer.custom')}</button></div>{customOpen?<div className="focus-timer__custom"><label htmlFor="focus-custom-minutes">{t('focusTimer.customMinutes')}</label><input id="focus-custom-minutes" className="focus-timer__custom-input" inputMode="numeric" value={custom} onChange={event=>setCustom(event.target.value)}/>{custom&&!customValid?<span role="alert">{t('focusTimer.customError')}</span>:null}<button className="btn" disabled={!customValid} onClick={()=>{setMinutes(customValue);setCustomOpen(false)}}>{t('focusTimer.useDuration')}</button></div>:null}<div className="focus-timer__actions">{!running&&!paused?<button className="btn btn-primary" aria-label={t('focusTimer.startFocus')} onClick={()=>void timer.start(minutes)}><Play aria-hidden="true"/>{t('focusTimer.startFocus')}</button>:<button className="btn btn-primary" onClick={()=>void(running?timer.pause():timer.resume())}>{running?<Pause aria-hidden="true"/>:<Play aria-hidden="true"/>}{running?t('focusTimer.pause'):t('focusTimer.resume')}</button>}<button className="btn btn-icon" aria-label={t('focusTimer.reset')} disabled={!running&&!paused} onClick={()=>void timer.interrupt()}><RotateCcw aria-hidden="true"/></button></div><button className="focus-timer__trend" onClick={onOpenStatistics}><span><strong>{Math.round(timer.statistics.data.totalFocusedSeconds/60)}</strong><small>{t('focusTimer.weekMinutes')}</small></span></button></div></div>
}
